### ISSUE TITLE
http-proxy-middleware must be required explicitly

### ISSUE THREAD

**Issue by nabrown** [MauricioRobayo/api-key-proxy-server#31]
I was getting an error that `proxy` was not a function. Eventually, I noticed in the [changelog for http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware/releases/tag/v1.0.0) that the require statement must now be written:

```
const { createProxyMiddleware } = require('http-proxy-middleware');
```

I changed this on line 1 of `src/proxies.js` and changed line 38 accordingly to be:
```
return createProxyMiddleware(filter, options)
```

Everything is now working! :-)

**Comment by MauricioRobayo** [comment]
Hey! Thanks @nabrown! I need to write some tests so it catches these issues on automatic updates.
