### ISSUE TITLE
changeOrigin not working

### ISSUE THREAD

**Issue by marcosvafilho** [MauricioRobayo/api-key-proxy-server#43]
Just had to deal with an API endpoint that throws a 403 status code if 'origin' is a third party host and it looks like the 'changeOrigin' option, used for proxy creation and intended for this situation, is actually not working.

Not totally sure where this issue actually belongs though. This repo? http-proxy-middleware?

My best. Thank you so much for your work :)

**Comment by MauricioRobayo** [comment]
Hi @marcosvafilho , thank you for taking the time to report this and sorry for the late response.

The `changeOrigin` option comes from [http-node-proxy](https://github.com/http-party/node-http-proxy#options). It is always enabled in this proxy 🤔 : https://github.com/MauricioRobayo/api-key-proxy-server/blob/c031794f02e6561dfab5536c5c477f4c17f3dad3/src/proxies.js#L23

You can check if it is working by subscribing to the [`proxyReq`](https://github.com/chimurai/http-proxy-middleware#http-proxy-events) event adding something like this to the options on the [proxies.js](https://github.com/MauricioRobayo/api-key-proxy-server/blob/c031794f02e6561dfab5536c5c477f4c17f3dad3/src/proxies.js) file:

```js
onProxyReq(proxyReq, req, res) {
  console.log(proxyReq.getHeaders())
},
```

You should be able to see if the `host` header chages to the target url, for example, with `changeOrigin: true`:

```
host: 'api.openweathermap.org'
```

With `chanegOrigin: false`:

```
host: 'localhost:5000'
```
