### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by Lornz-** [MauricioRobayo/api-key-proxy-server#49]
Hi there, I tested the proxy server in a local machine with the _Open Weather API_ and my own `WEATHER_API_KEY` set in `.env` file but all I got is a `404` code from the server. I try to debug but I have no clue if it comes from the code itself or the `http-proxy-middleware`. Do you have any idea about what could possibly go wrong?

**Comment by MauricioRobayo** [comment]
Hi, sorry for the late response.

Make sure you are making the request from an allowed domain (can be localhost on another port). If you open the browser and you try to hit your endpoint you'll get a 404 as you are not making the request from an allowed domain.

All requests not made from an allowed domain will return a 404.

**Comment by marcosvafilho** [comment]
Hey @MauricioRobayo ... Any way to allow any and all domains instead of specific ones? Just for local development and tests? For some reason I cannot get any response other than 404 when trying to debug locally, no matter what I try, as opposed to when I push to heroku and use my real domain...

**Comment by MauricioRobayo** [comment]
> Hey @MauricioRobayo ... Any way to allow any and all domains instead of specific ones? Just for local development and tests? For some reason I cannot get any response other than 404 when trying to debug locally, no matter what I try, as opposed to when I push to heroku and use my real domain...

Moved [here](https://github.com/MauricioRobayo/API-Key-Proxy-Server/issues/70).
