### ISSUE TITLE
Feature Request: Rate Limiting

### ISSUE THREAD

**Issue by eeintech** [MauricioRobayo/api-key-proxy-server#72]
Hello @MauricioRobayo 

First: Wow!! I was looking to hide a third-party API key for one of my tools and I found your simple and amazing implementation.
I created an Heroku account/app, cloned your directory, updated the settings and deployed... all this in a matter of 5 minutes and BINGO I was making API request with no (visible) token! Well done :clap: :clap: 

Alright now time for me to suggest a feature I am also interested in: **rate limiting**.
I would like to plug the heroku app API calls into one of my open-source projects, and of course the concern is to limit the number of requests as I don't want any abuse on that third-party API. In the simplest form, it can just be a simple integer parameter to set the maximum number of requests per minute.
Or, in a more _elegant_ approach, it could be a per-user setting, with each user having a unique ID appended to the API parameters to look-up their current usage.

Given this means storing the number of requests somewhere, it might (or might not) involve database type of setup, maybe hopefully just a memory table which is reset every minute? I'm not an expert on that, I just know this could be the main concern for this feature.

Anyway, I hope it sparks ideas on your side, I would love to see this implemented in any form :smiley: 

And again, fantastic job! :partying_face:

**Comment by MauricioRobayo** [comment]
Hi @eeintech ! Thanks for your kind words and for opening the issue. That's a great suggestion, we could use a npm package for that, for example, https://www.npmjs.com/package/express-rate-limit.

I'm a little short of time at this moment, but the suggestion is great so I've added the `good first issue` tag so maybe someone (you included 😄 ) can pick it up.

**Comment by eeintech** [comment]
This package looks like a good fit indeed! Great find!

Unfortunately I'm not very familiar with JS/TypeScript, it's probably better for someone else to pick up the reward 😄

**Comment by MauricioRobayo** [comment]
I'm archiving this project as no longer able to work at it. 😞
