### ISSUE TITLE
Only allow calls from my mobile app

### ISSUE THREAD

**Issue by divinemaredi** [MauricioRobayo/api-key-proxy-server#73]
Hi there

I'd like to use this proxy server (great job btw) for my mobile app. I saw that there's an option to insert the allowed domains, and I suppose this works for a web app making the calls.

But my app will initially run on Android and iOS and a web-based version will come later, so I just wanted to know if there's a way to only allow calls coming from my mobile clients?

Thanks again!

**Comment by MauricioRobayo** [comment]
Hi @divinemaredi , I'm sorry for the late response.

I don't have any idea about mobile clients and currently don't have the time to dig into it, so I won't be able to help you.

Am going to archive this project as I'm no longer able to work at it.

😞
